#pragma once

#include <stddef.h>
#include <stdint.h>

static constexpr const char *MQTT_TOPIC_ROOT = "voda/septik";

enum class mqtt_topic_id_t : uint16_t {
    TOPIC_STAV_ZASOBA_OBJEM = 0,
    TOPIC_STAV_ZASOBA_HLADINA,
    TOPIC_STAV_CERPANI_PRUTOK,
    TOPIC_STAV_CERPANI_CERPANO_CELKEM,
    TOPIC_STAV_TEPLOTA_VODA,
    TOPIC_STAV_TEPLOTA_VZDUCH,
    TOPIC_STAV_TLAK_PRED_FILTREM,
    TOPIC_STAV_TLAK_ZA_FILTREM,
    TOPIC_STAV_ROZDIL_TLAKU_FILTRU,
    TOPIC_STAV_ZANESENOST_FILTRU_PERCENT,
    TOPIC_STAV_CERPANI_PUMPA_STAV,
    TOPIC_ELEKTRO_CERPADLO_NAPETI_V,
    TOPIC_ELEKTRO_CERPADLO_PROUD_A,
    TOPIC_ELEKTRO_CERPADLO_VYKON_CINNY_W,
    TOPIC_ELEKTRO_CERPADLO_VYKON_JALOVY_VAR,
    TOPIC_ELEKTRO_CERPADLO_VYKON_ZDANLIVY_VA,
    TOPIC_ELEKTRO_CERPADLO_FREKVENCE_HZ,
    TOPIC_ELEKTRO_CERPADLO_COSFI,
    TOPIC_ELEKTRO_CERPADLO_ENERGIE_CINNA_KWH,
    TOPIC_ELEKTRO_CERPADLO_ENERGIE_JALOVA_KVARH,

    TOPIC_SYSTEM_STATUS,
    TOPIC_SYSTEM_BOOT_MODE,
    TOPIC_SYSTEM_OTA_EVENT,
    TOPIC_SYSTEM_OTA_PROGRESS,
    TOPIC_SYSTEM_REBOOT_REASON,
    TOPIC_SYSTEM_REBOOT_COUNTER,
    TOPIC_SYSTEM_LAST_DISCONNECT_DURATION_S,

    TOPIC_DIAG_FW_VERSION,
    TOPIC_DIAG_BUILD_TIMESTAMP,
    TOPIC_DIAG_GIT_HASH,
    TOPIC_DIAG_UPTIME_S,
    TOPIC_DIAG_WIFI_RSSI_DBM,
    TOPIC_DIAG_WIFI_RECONNECT_TRY,
    TOPIC_DIAG_WIFI_RECONNECT_SUCCESS,
    TOPIC_DIAG_WIFI_CONNECTS,
    TOPIC_DIAG_WIFI_DISCONNECTS,
    TOPIC_DIAG_MQTT_CONNECTS,
    TOPIC_DIAG_MQTT_DISCONNECTS,
    TOPIC_DIAG_MQTT_RECONNECTS,
    TOPIC_DIAG_LAST_MQTT_RC,
    TOPIC_DIAG_HEAP_FREE_B,
    TOPIC_DIAG_HEAP_MIN_FREE_B,
    TOPIC_DIAG_NVS_ERRORS,
    TOPIC_DIAG_ADS1115_STATUS,
    TOPIC_DIAG_ADS1115_READ_ERRORS,
    TOPIC_DIAG_ADS1115_LAST_OK_AGE_S,
    TOPIC_DIAG_MODBUS_KWS_STATUS,
    TOPIC_DIAG_MODBUS_KWS_TIMEOUTS,
    TOPIC_DIAG_MODBUS_KWS_CRC_ERRORS,
    TOPIC_DIAG_MODBUS_KWS_READ_ERRORS,
    TOPIC_DIAG_MODBUS_KWS_LAST_OK_AGE_S,
    TOPIC_DIAG_TEPLOTA_STATUS,
    TOPIC_DIAG_TEPLOTA_BUS_ERRORS,
    TOPIC_DIAG_TEPLOTA_CRC_ERRORS,
    TOPIC_DIAG_TEPLOTA_READ_ERRORS,
    TOPIC_DIAG_TEPLOTA_LAST_OK_AGE_S,
    TOPIC_DIAG_SENSOR_QUEUE_DROPS,
    TOPIC_DIAG_MQTT_PUBLISH_QUEUE_DROPS,
    TOPIC_DIAG_TEPLOTA_SCAN,

    TOPIC_CMD_REBOOT,
    TOPIC_CMD_WEBAPP,
    TOPIC_CMD_DEBUG,
    TOPIC_CMD_LOG_LEVEL,
    TOPIC_CMD_OTA_START,
    TOPIC_CMD_OTA_CONFIRM,
    TOPIC_CMD_TEPLOTA_SCAN,

    COUNT,
};

enum class mqtt_topic_direction_t : uint8_t {
    PUBLISH_ONLY = 0,
    SUBSCRIBE_ONLY,
};

enum class mqtt_payload_kind_t : uint8_t {
    NUMBER = 0,
    BOOLEAN,
    TEXT,
    JSON,
};

struct mqtt_topic_descriptor_t {
    mqtt_topic_id_t id;
    const char *full_topic;

    mqtt_topic_direction_t direction;
    mqtt_payload_kind_t payload_kind;
    uint8_t qos;
    bool retain;
};

extern const mqtt_topic_descriptor_t MQTT_TOPIC_TABLE[(size_t)mqtt_topic_id_t::COUNT];

const mqtt_topic_descriptor_t *mqtt_topic_descriptor(mqtt_topic_id_t id);
