name: Build firmware

on:
  push:
    branches: ["**"]
    paths:
      - "firmware/**"
  pull_request:
    paths:
      - "firmware/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.2
          target: esp32
          path: firmware

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            firmware/build/voda-septik.bin
            firmware/build/bootloader/bootloader.bin
            firmware/build/partition_table/partition-table.bin
